.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH MUSIC 1 "March  5, 2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
music_tests \- run MUSIC tests
.SH SYNOPSIS
.B music_tests
.RI [ options ]
.SH DESCRIPTION
Run a suite of tests validating the correct operation of MUSIC.
.SH OPTIONS
.B \-\-help
Show program options and exit.
.TP
.B \-\-showme\-tests
Print test names and exit.
.TP
.B \-\-output\-dir=<PATH>
Output directory (default: ./reports).
.SH SEE ALSO
.BR music (1).
.\" .br
.\" The programs are documented fully by
.\" .IR "The Rise and Fall of a Fooish Bar" ,
.\" available via the Info system.
.SH AUTHOR
music_tests was written by Ekaterina Brocke..
.PP
This manual page was written by Mikael Djurfeldt <mdj@debian.org>,
for the Debian project (but may be used by others).
